apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-web
  labels:
    kiamol: ch19
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-web
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
