---

- hosts: all
  remote_user: centos
  become: yes
  become_method: sudo
  tasks:
   - name: Install all the packages
     yum:
       name: ['epel-release', 'telnet', 'xauth']
       state: present
       update_cache: True

