apiVersion: v1
kind: PersistentVolume
metadata:
  name: test
  labels:
    app: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfsserver.example.com
    # Exported path of your NFS server dont forget to change the above line
    path: "/mydbdata"

